### ISSUE TITLE
Grundstruktur für die Entwicklung eines eigenen QGIS-Plugins für die Visualisierung unterschiedlicher Datensätze

### ISSUE THREAD

**Issue by saschadoemer** [vitrum-connect/5gla-qgis#10]
**Beschreibung**

Als Entwickler möchte ich eine zentrale Grundstruktur im GitHub erstellen, konfigurieren und dokumentieren, um die Entwicklung von QGIS-Plugins zu vereinfachen, die unterschiedliche Datensätze aus einer mit FIWARE verknüpften PostgreSQL-Datenbank visualisieren. Diese Struktur soll als Ausgangspunkt für die Entwicklung dienen und eine einheitliche Vorgehensweise bei der Plugin-Entwicklung fördern. Die Dokumentation soll klare Anweisungen zur Nutzung der Struktur bieten, inklusive Richtlinien zur Integration von FIWARE und PostgreSQL, um die Entwicklungseffizienz zu steigern und die Qualität der erstellten Plugins zu sichern.

**Akzeptanzkriterien**

Damit die User Story erfolgreich umgesetzt ist, wird erwartet ...

- ... dass ein GitHub-Repository erstellt wird, welches die zentrale Grundstruktur für die Entwicklung von QGIS-Plugins beinhaltet.
- ... dass die Grundstruktur die Integration mit einer PostGIS-Datenbank, die über FIWARE verknüpft ist, unterstützt und erleichtert.
- ... dass im Repository eine detaillierte Dokumentation vorhanden ist, die beschreibt, wie die Struktur zu nutzen ist, einschließlich Anleitungen zur Konfiguration der Verbindung zu FIWARE und PostGIS.

**Comment by Vitrum-LL** [comment]
Hast du eine Idee wie ich die Credentials sinnvoll vom Code trennen? Derzeit hab ich erstmal User Inputfelder für Passwort usw.

**Comment by Vitrum-LL** [comment]
> Hast du eine Idee wie ich die Credentials sinnvoll vom Code trennen? Derzeit hab ich erstmal User Inputfelder für Passwort usw.

Ich würde es wie abgesprochen in einer Qgis Settings config speichern.

**Comment by Vitrum-LL** [comment]
Musste es nochmal ne Woche nach hinten schieben.

**Comment by Vitrum-LL** [comment]
Krankheitsbedingt weiter nachhinten geschoben.

**Comment by saschadoemer** [comment]
@Vitrum-LL ich habe den korrekten PR verlinkt, nur eben zur Info.

**Comment by saschadoemer** [comment]
Verlinkungen aktualisiert.
