### ISSUE TITLE
Visualisierung der Bodenfeuchte anhand der absoluten Messwerte in den unterschiedlichen Tiefen für die Agvolution-Sensoren in QGIS

### ISSUE THREAD

**Issue by saschadoemer** [vitrum-connect/5gla-qgis#3]
**Beschreibung**

Als Landwirt möchte ich die Bodenfeuchte in verschiedenen Tiefen anhand der absoluten Messwerte visualisieren, die durch die Agvolution-Sensoren erfasst werden, um Einblicke in die Feuchtigkeitsverteilung im Boden zu erhalten. Dies soll innerhalb der QGIS-Plattform realisiert werden, damit ich die Daten in bestehende geografische Informationssysteme (GIS) integrieren kann. Die Visualisierung soll mir ermöglichen, Muster und Trends der Bodenfeuchtigkeit leichter zu erkennen, was für die Planung von Bewässerungsmaßnahmen und zur Verbesserung des Wassermanagements unerlässlich ist.

**Akzeptanzkriterien**

Damit die User Story erfolgreich umgesetzt ist, wird erwartet ...

- ... dass die Visualisierung für die verschiedenen Tiefenstufen des Sensors möglich ist.
- ... dass die Messwerte der Agvolution-Sensoren korrekt in die QGIS-Plattform importiert werden können.
- ... dass die Tiefe anhand einer Farbskala dargestellt wird, wobei unterschiedliche Farben verschiedene Tiefe repräsentieren.

**Comment by Vitrum-LL** [comment]
Zurückgestellt. Fertigstellung device_position priorisiert.
